mybatis:
  #config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.turbine.tnd.*
  configuration:
    map-underscore-to-camel-case: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 990508
    url: jdbc:mysql://127.0.0.1:3306/tnd?characterEncoding=UTF-8


      #servlet:
   #multipart:
      #max-file-size: 1MB
     #max-request-size: 900MB
logging:
  level:
    com.turbine.*: debug
